-- Generated from generator/demo_specs/aws-vietnam-aquaculture-export.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-aquaculture-export
-- This is the schema that is actually deployed for VIETNAM_AQUACULTURE_EXPORT.

-- Alerts fire on the bottom tail of Avg Price/kg
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_AVG_PRICE_KG) AS T
  FROM RAW.EXPORT_SHIPMENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_AVG_PRICE_KG <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_AVG_PRICE_KG), 2) AS AVG_PRICE_KG,
  ROUND(AVG(f.KPI_REJECTION_RATE), 2) AS AVG_REJECTION_RATE
FROM RAW.EXPORT_SHIPMENTS f
JOIN RAW.FARMS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_AVG_PRICE_KG), 2) AS AVG_PRICE_KG,
  ROUND(AVG(f.KPI_REJECTION_RATE), 2) AS AVG_REJECTION_RATE
FROM RAW.EXPORT_SHIPMENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_REJECTION_RATE) AS KPI_REJECTION_RATE, AVG(KPI_AVG_PRICE_KG) AS KPI_AVG_PRICE_KG FROM RAW.EXPORT_SHIPMENTS),
     en AS (SELECT SUM(KPI_EXPORT_REVENUE) AS KPI_EXPORT_REVENUE, SUM(KPI_SHIPMENTS_MTD) AS KPI_SHIPMENTS_MTD, SUM(KPI_MARKETS_ACTIVE) AS KPI_MARKETS_ACTIVE FROM RAW.FARMS)
  SELECT 1 AS SORT_ORDER, 'Export Revenue' AS TITLE, KPI_EXPORT_REVENUE AS VALUE_NUM, '₫' || TO_VARCHAR(CAST(ROUND(((KPI_EXPORT_REVENUE) / 1000000000000), 1) AS DECIMAL(38,1))) || 'T' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Shipments (MTD)' AS TITLE, KPI_SHIPMENTS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SHIPMENTS_MTD)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Rejection Rate' AS TITLE, KPI_REJECTION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_REJECTION_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Markets Active' AS TITLE, KPI_MARKETS_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MARKETS_ACTIVE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Price/kg' AS TITLE, KPI_AVG_PRICE_KG AS VALUE_NUM, '₫' || TO_VARCHAR(CAST(ROUND(((KPI_AVG_PRICE_KG) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
