-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Export Compliance
-- ============================================================================
USE DATABASE AQUACULTURE_EXPORT;
USE SCHEMA ML;

-- ML.FORECAST: AQUACULTURE_EXPORT_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.AQUACULTURE_EXPORT_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FORECAST_INPUT'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.AQUACULTURE_EXPORT_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.AQUACULTURE_EXPORT_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: AQUACULTURE_EXPORT_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.AQUACULTURE_EXPORT_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.AQUACULTURE_EXPORT_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.AQUACULTURE_EXPORT_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'), SERIES_COLNAME => 'ENTITY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

